### ISSUE TITLE
Shadow DOM breaks package

### ISSUE THREAD

**Issue by adamrunner** [Alchiadus/base16-syntax#5] opened 2015-01-07 17:51 UTC
In Atom 0.166.0, they enabled "Shadow DOM" by default. 

http://blog.atom.io/2015/01/05/enable-shadow-dom.html

This seems to break all of the base16-syntax themes.

**Comment by Alchiadus** [comment] 2015-01-07 20:21
Duplicate of #4.

**Closed by Alchiadus** 2015-01-07 20:21 UTC
